/**
 * Created by Zero on 2018/3/27
 */
import {StyleSheet} from 'react-native';
import Util from './../../../js/util';

const refundStyle = StyleSheet.create({

    list:{
        width:"100%",
        paddingLeft:15,
        paddingRight:15,
        borderTopColor:"#e6e6e6",
        borderTopWidth:1,
        backgroundColor:"#fff",
        paddingTop:10,
        paddingBottom:10,
    },
    imageL:{
        width:100,
        height:100,
        marginBottom:10,
    },
    imgItem:{
        position:'relative',
        marginRight:5,
        width:120,
        height:120,
    },
    rightDelButton:{
        width:20,
        height:20,
        position:'absolute',
        top:-10,
        left:100,
        zIndex:9999
    },
    imgBox:{
        flexDirection:'row',
        flexWrap:'wrap',
        marginLeft:10,
        marginTop:15
    },
    refundInputWrap:{
        width:"100%",
        height:50,
        marginTop:10,
        backgroundColor:"red"
    },
    refundInput:{
        backgroundColor:"#f0f2f5",
        height:"100%",
        padding:0,
        fontSize:14,
    },
    imgWrap:{
        // marginTop:15,
        // marginBottom:5,
        // flexDirection:"row",
    },
    img:{
        marginRight:7,
    },
    detailsTitle:{
        backgroundColor:'#20a200',
        paddingLeft:15,
        paddingTop:19,
        paddingBottom:20,
    },
    serInfo:{
        backgroundColor:'#fff',
        paddingLeft:15,
        paddingRight:15,
        paddingTop:15,
        paddingBottom:15,
        marginBottom:10
    },
    serInfos:{
        display:'none'
    },
    green:{
        color:'#20a200'
    },
    sendBtn:{
        flexDirection:'row',
        alignItems: 'center',
        justifyContent:'center',
        borderTopColor:'#ddd',
        borderTopWidth:1,
        paddingTop:15,
        paddingBottom:15
    },
    btnItm:{
        paddingTop:5,
        paddingBottom:5,
        paddingLeft:10,
        paddingRight:10,
        color:'#000'
    },
    centers5:{
        backgroundColor:'#fff',
        paddingTop:10,
        paddingBottom:15,
        marginTop:0,
        marginBottom:40
    },
   centers:{
        backgroundColor:'#fff',
        paddingTop:10,
        paddingBottom:15,
        marginTop:10,
        marginBottom:40
   },
   centerBox:{
         backgroundColor:'#f9f9f9',
         flexDirection:'column',
         alignItems:'flex-end',
   },
   center:{
       backgroundColor:'#f9f9f9',
       paddingLeft:15,
       flexDirection:'row',
       marginBottom:14,
       justifyContent: 'space-between',
       paddingTop:10,
       paddingBottom:10,
       alignItems:'center',
   },
   sendInfo:{
       backgroundColor:'#fff',
   },
   sendItem:{
        flexDirection:'row',
        paddingTop:15,
        paddingBottom:15,
        paddingLeft:15,
        paddingRight:15,
   },
   listLeft:{
       width:67,
       height:67,
       borderRadius:3,
   },
   listRight:{
       marginLeft:15,
       marginRight:15,
       width:'70%'
   },
   Color99:{
       color:'#999'
   },
   chooseItem:{
        borderBottomColor:'#ddd',
        backgroundColor:'#fff',
        borderBottomWidth:1,
        paddingLeft:15,
        paddingRight:15,
        paddingTop:15,
        paddingBottom:15,
        flexDirection:'row',
        justifyContent: 'space-between',
   },
   chooseItemLast:{
        borderBottomColor:'#ddd',
        backgroundColor:'#fff',
        borderBottomWidth:1,
        paddingTop:15,
        paddingBottom:15,
   },
   DateContent:{
        backgroundColor:'#fff',
        paddingLeft:15,
        paddingRight:15,
        paddingBottom:25,
   },
   dayBox:{
        flexDirection:'row',
        alignItems:'center',
        flexWrap: 'wrap',
        marginTop:20,
        marginBottom:50
   },
   dateItem:{
        flexDirection:'row',
        alignItems:'center',
        marginBottom:18,
        marginRight:17
   }
});
export default refundStyle;