/**
 * Created by juaner on 2018/3/27.
 */
import {StyleSheet} from 'react-native';
import Util from './../../../js/util';

const OrderStyle = StyleSheet.create({
    content:{
        backgroundColor:'#f0f2f5',
        paddingTop:10,
    },
    Item:{
        backgroundColor:'#fff',
        paddingTop:17,
        borderBottomWidth:1,
        borderBottomColor:'#ddd',
        marginBottom:5
    },
    NoBox:{
        paddingLeft:15,
        paddingRight:15,
        marginBottom:15,
        flexDirection:'row',
        justifyContent: 'space-between',
    },
    Color99:{
        color:'#999'
    },
    center1:{
        backgroundColor:'#f9f9f9',
        paddingLeft:15,
        flexDirection:'row',
        marginBottom:14,
        justifyContent: 'flex-start',
        paddingTop:10,
        paddingBottom:10,
        alignItems:'center',
    },
    center:{
        backgroundColor:'#f9f9f9',
        paddingLeft:15,
        flexDirection:'row',
        marginBottom:14,
        justifyContent: 'space-between',
        paddingTop:10,
        paddingBottom:10,
        alignItems:'center',
    },
    centerBox:{
         backgroundColor:'#f9f9f9',
         flexDirection:'column',
         alignItems:'flex-end',
    },
    listLeft:{
        width:67,
        height:67,
        borderRadius:3,
    },
    listRight:{
        marginLeft:15,
        marginRight:15,
        width:'70%'
    },
    btnBox:{
         flexDirection:'row',
         alignItems:'center',
         justifyContent: 'flex-end',
         paddingRight:15,
         marginBottom:5
    },
    btnBox2:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent: 'space-between',
        paddingRight:15,
        marginBottom:5,
        paddingLeft:15,
    },
    btnBoxRefund:{
        flexDirection:'row',
        alignItems:'center',
        marginRight:15,
        marginBottom:5,
        marginLeft:15,
        justifyContent: 'space-between',
    },
    btnSuccess:{
        color:'#20a200'
    },
    btnItm:{
        paddingTop:5,
        paddingBottom:5,
        paddingLeft:10,
        paddingRight:10,
        color:'#000'
    },
    btnBorder:{
        borderColor:'#000',
        borderWidth:1
    },
    refund:{
        flexDirection:'row',
    },
    detailsTitle:{
        backgroundColor:'#20a200',
        paddingLeft:15,
        paddingTop:19,
        paddingBottom:20,
    },
    serInfo:{
        backgroundColor:'#fff',
        paddingLeft:15,
        paddingRight:15,
        paddingTop:15,
        paddingBottom:15,
    },
    location:{
        flexDirection:'row',
        alignItems:'center',
        marginTop:15
    },
    isPay:{
        flexDirection:'row',
        justifyContent: 'space-between',
        paddingLeft:15,
        paddingRight:15,
        paddingTop:15,
        paddingBottom:15,
        borderTopColor:'#ddd',
        borderTopWidth:1
    },
    receipt:{
        marginTop:10,
        paddingTop:15,
        paddingBottom:15,
        backgroundColor:'#fff',
        marginBottom:52
    },
    receiptText:{
        paddingLeft:15,
        paddingRight:15,
        paddingBottom:15,
        borderBottomWidth:1,
        borderBottomColor:'#ddd'
    },
    detailsBtn:{
        backgroundColor:'#fff',
        paddingTop:10,
        paddingBottom:10
    },
    orderTime:{
        borderBottomColor:'#ddd',
        borderBottomWidth:1,
        paddingTop:15,
        paddingBottom:15,
        paddingLeft:15
    },
    green:{
        color:'#20a200'
    },
    sendInfo:{
        backgroundColor:'#fff',
    },
    sendItem:{
         flexDirection:'row',
         paddingTop:15,
         paddingBottom:15,
         paddingLeft:15,
         paddingRight:15,
    },
    sendBtn:{
        flexDirection:'row',
        alignItems: 'center',
        justifyContent:'center',
        borderTopColor:'#ddd',
        borderTopWidth:1,
        paddingTop:15,
        paddingBottom:15
    },
    centers:{
        backgroundColor:'#fff',
        paddingTop:10,
        paddingBottom:15,
        marginTop:10,
        marginBottom:40
    }
});
export default OrderStyle;