/**
 * Created by yangHL on 2018/3/23.
 */
import {StyleSheet} from 'react-native';
import Util from './../../../js/util';
import px2dp from './../../../js/px2dp'

const commodityStyle = StyleSheet.create({
    swiper:{
        width:Util.size.width
    },
    content:{
        paddingLeft:15,
        paddingRight:15,
        backgroundColor:'#ffffff',
        paddingBottom:15,
        borderBottomWidth:1,
        borderBottomColor:'#e6e6e6'
    },
    contentTitle:{
        marginTop:15
    },
    titleText:{
        color:"#000000",
        fontSize:16
    },
    contentPrice:{
        flexDirection:'row',
        marginTop:14,
        justifyContent:'space-between',
        alignItems:"flex-end"
    },
    contentLeft:{
        flexDirection:'row',
        alignItems:"flex-end"
    },
    priceText:{
        fontSize:16,
        color:"#ff4e3c",
        fontWeight:'bold'
    },
    priceTypeText:{
        color:'#ff4e3c',
        fontSize:12,
        borderWidth:1,
        borderColor:'#ff4e3c',
        borderRadius:2,
        paddingLeft:1,
        paddingRight:1,
        marginLeft:10,
    },
    priceVIPText:{
        marginLeft:10,
        fontSize:11,
    },
    surplusText:{
        color:'#999999',
        fontSize:12
    },
    activity:{
        paddingLeft:15,
        paddingRight:15,
        flexDirection:'row',
        paddingTop:14,
        paddingBottom:14,
        borderBottomWidth:1,
        borderBottomColor:'#e6e6e6',
        justifyContent:'space-around',
        alignItems:"flex-start",
        backgroundColor:'#ffffff'
    },
    activityType:{
        flexDirection:'row',
    },
    activityTitle:{
        color:'#999999',
        fontSize:12,
    },
    activityContent:{
        marginLeft:15
    },
    activityTypeContent:{
        marginLeft:5,
        fontSize:12,
        overflow:'hidden',
        // textOverflow:'ellipsis',
        // whiteSpace:'nowrap',
    },
    activityTypeOne:{
        color:'#ff4e3c',
        borderWidth:1,
        borderColor:'#ff4e3c',
        borderRadius:2,
        paddingLeft:1,
        paddingRight:1,
        fontSize:11
    },
    activityTypeTwo:{
        color:'#ff8f3c',
        borderWidth:1,
        borderColor:'#ff8f3c',
        borderRadius:2,
        paddingLeft:1,
        paddingRight:1,
        fontSize:11
    },
    activityTypeThree:{
        color:'#20a200',
        borderWidth:1,
        borderColor:'#20a200',
        borderRadius:2,
        paddingLeft:1,
        paddingRight:1,
        fontSize:11
    },
    service:{
        flexDirection:'row',
        paddingLeft:15,
        paddingRight:15,
        backgroundColor:'#ffffff',
        paddingTop:14,
        paddingBottom:14,
    },
    serviceContent:{
        flexDirection:'row',
        alignItems:'center'
    },
    line:{
        height:10,
        backgroundColor:'#f0f2f5',
        borderBottomWidth:1,
        borderBottomColor:'#e6e6e6',
    },
    specifications:{
        flexDirection:'row',
        paddingLeft:15,
        paddingRight:15,
        backgroundColor:'#ffffff',
        paddingTop:14,
        paddingBottom:14,
        alignItems:'center',
        justifyContent:'space-between',
    },
    specificationsContent:{
        flexDirection:'row',
        alignItems:'center',
    },
    specificationsChoice:{
        color:'#999999',
        fontSize:12
    },
    specificationsText:{
        marginLeft:14,
        fontSize:13
    },
    specificationsButton:{
        backgroundColor:'#ffffff',
        paddingTop:5,
        borderWidth:1,
        height:23,
        borderColor:'#838383',
        marginRight:12,
        shadowRadius:0
    },
    reduceNum:{
        width:20,
        height:20,
        backgroundColor:"#dcdcdc",
        borderRadius:3,
    },
    numTextWrap:{
        width:50,
        height:20,

    },
    numText:{
        textAlign:"center",
        lineHeight:20,
        fontSize:14,
    },
    selNumText:{
        padding:0,
        width:"100%",
        height:"100%",
        lineHeight:20,
        textAlign:"center",
        fontSize:14
    },
    shop:{
        backgroundColor:'#ffffff',
        height:50,
        position:'absolute',
        bottom:0,
        width:'100%',
        flexDirection:'row',
        borderBottomWidth:1,
        borderBottomColor:'#e6e6e6',
        borderTopWidth:1,
        borderTopColor:'#e6e6e6'
    },
    collection:{
        flex:2,
        backgroundColor:'#fff',
        margin:'auto',
        justifyContent:'center',
        alignItems:'center'
    },
    add:{
        flex:4,
        backgroundColor:'#fff',
        borderLeftWidth:1,
        borderLeftColor:'#e6e6e6',
        justifyContent:'center',
        alignItems:'center'
    },
    background:{
        flex:1,
        borderLeftWidth:1,
        borderLeftColor:'#e6e6e6',
        justifyContent:'center',
        alignItems:'center'
    },
    modalAll:{
        height:196
    }
});
export default commodityStyle;