import {StyleSheet} from 'react-native';
import Util from './../../js/util';

const MineStyle = StyleSheet.create({
    titleBox:{
        width:Util.width,
    },
    title:{
        flexDirection:'row',
        justifyContent:'center',
        marginTop:12.5
    },
    write:{
        color:'#fff',
        fontSize:14
    },
    setting:{
        color:'#fff',
        textAlign:'right',
        flex:1,
        paddingRight:18
    },
    infoBox:{
       flexDirection:'row',
       justifyContent: 'space-between',
       marginTop:35,
       alignItems:'center',
       marginBottom:33
    },
    info:{
        marginLeft:15,
        flexDirection:'row',
        alignItems:'center'
    },
    infoImg:{
        borderRadius:50,
        width:50,
        height:50,
        marginRight:15
    },
    infoImg2:{
        borderRadius:50,
        width:35,
        height:35,
        marginRight:10
    },
    integral:{
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        color:'#fff',
        paddingTop:2.5,
        paddingBottom:5,
        paddingLeft:10,
        paddingRight:10,
        marginRight:15,
        borderRadius:30,
        fontSize:12
    },
    navBox:{
        flexDirection:'row',
        alignItems:'center',
        backgroundColor:'#fff',
        justifyContent:'space-around',
        marginBottom:11,
    },
    navItem:{
        justifyContent:'center',
        marginTop:16,
        marginBottom:20,
        alignItems:'center'
    },
    NavNum:{
        fontSize:11,
        marginBottom:10
    },
    navImg:{
        marginBottom:5
    },
    orderBox:{
        backgroundColor:'#fff',
        paddingLeft:15,
        paddingRight:15
    },
    orderTitle:{
       flexDirection:'row',
       paddingTop:14,
       justifyContent: 'space-between',
       marginBottom:14
    },
    orderItemBox:{
       flexDirection:'row',
       justifyContent:'space-around',
       borderColor:'#ddd',
       borderWidth:1,
       borderRadius:3,
       marginBottom:15,
       shadowColor:'red',
       shadowOffset:{width:13,height:23},
       shadowRadius:33,
       shadowOpacity:0.8,
       elevation: 4,
    },
    orderItem:{
        justifyContent:'center',
        paddingTop:20,
        paddingBottom:14,
        alignItems:'center'
    },
    alertNum:{
        color:'red',
        position:'absolute',
        top:-5,
        right:0
    },
    ListBox:{
        backgroundColor:'#fff',
        marginTop:11,
        paddingLeft:15,
        justifyContent: 'space-between',
        flexDirection:'row',
        alignItems:'center',
        paddingRight:15,
        paddingTop:12,
        paddingBottom:12,
        borderBottomWidth:1,
        borderBottomColor:'#ddd'
    },
    ListIcon:{
        marginRight:9,
    },
    ListItem:{
        borderBottomWidth:1,
        borderColor:'#ddd',
        paddingLeft:0
    },
    settingList:{
        backgroundColor:'#fff',
        marginBottom:11
    },
    settinglistItem:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        padding:15,
        borderBottomWidth:1,
        borderBottomColor:'#ddd',
    },
    contentChange:{
        backgroundColor:'#fff',
    },
    borderRight:{
        width:30,
        borderRightColor:'#e5e5e5',
        borderRightWidth:1,
        flexDirection:'row',
        alignItems:"center",
        justifyContent:"center"
    },
    iconImg:{
        // width:20,
        // height:20,
    },
    inputF:{
        paddingLeft:0,
        marginLeft:0,
        backgroundColor:'#fff',
    },
    inputRealName:{
        paddingLeft:10,
        marginLeft:0,
        backgroundColor:'#fff',
    },
    input:{
        backgroundColor:'#fff',
    },
    inputCenter:{
         backgroundColor:'#fff',
         marginTop:10,
         marginBottom:10,
    },
    borderedButton:{
        alignSelf:'center',
        marginRight:10,
    },
    QRContent:{
        backgroundColor:'#fff'
    },
    QRBox:{
        justifyContent:'center',
        alignItems:'center'
    },
    QRCodeImg:{
        marginTop:31,
        marginBottom:21
    },
    realName:{
        backgroundColor:'#fff'
    },
    uploadImage:{
        width:232,
        height:146
    },
    uploadImages:{
        paddingLeft:52.5,
        marginBottom:20,
        paddingRight:52.5,
        backgroundColor:'#f5f7fa',
        borderRadius:5,
        justifyContent:'center',
        alignItems:'center'
    },
    memberContent:{
        backgroundColor:'#fff',
        paddingRight:15,
        paddingLeft:15,
    },
    memberBox:{
        marginBottom:50,
    },

});
export default MineStyle;