/**
 * Created by yangHL on 2018/3/28.
 */
import React from 'react';
import {StyleSheet} from 'react-native';
import util from './../../../../js/util'
const commentDetailsStyle=StyleSheet.create({
    commentList:{
        paddingTop:15,
        paddingRight:15,
        paddingBottom:15,
        borderBottomWidth:1,
        borderBottomColor:'#e6e6e6'
    },
    commentOne:{
        paddingLeft:15,
        flexDirection:'row',
        justifyContent: 'space-between',
        alignItems:'flex-start',
    },
    commentOneLeft:{
        flexDirection:'row',
        alignItems:'center',
    },
    user:{
        marginLeft:16,
    },
    userName:{
        fontSize:13
    },
    userStar:{
        marginTop:5,
        flexDirection:'row',
    },
    commentOneRight:{
        flexDirection:'row',
    },
    commentContent:{
        paddingLeft:15,
        fontSize:13,
        marginTop:15,
    },
    imgesAll:{
        marginTop:6,
        flexDirection:'row',
        flexWrap:'wrap',
        paddingLeft:10
    },
    imagesSingle:{
        // flex:3
        marginLeft:5,
        marginTop:5,
    },
    commodity:{
        padding:15,
        borderBottomWidth:1,
        borderBottomColor:'#e7e7e7'
    },
    commodityOne:{
        flexDirection:'row'
    },
    commodityTwo:{
        flexDirection:'row',
        marginTop:10,
        alignItems:'center'
    },
    commodityDescribe:{
        marginLeft:10,
        marginRight:"20%"
    },
    line:{
        height:10,
        backgroundColor:'#eceff7',
        borderBottomWidth:1,
        borderBottomColor:'#e7e7e7'
    },
    commentTitle:{
        paddingTop:15,
        marginLeft:15,
        paddingRight:15,
        paddingBottom:5,
        fontSize:13,
        borderBottomWidth:1,
        borderBottomColor:'#e7e7e7'
    },
    commentAll:{
        padding:15,
        borderBottomWidth:1,
        borderBottomColor:'#e7e7e7'
    },
    commentListOne:{
        flexDirection:'row',
        justifyContent: 'space-between',
        alignItems:'flex-start',
    },
    button:{
        flexDirection:'row',
        position:'absolute',
        bottom:0,
        width:util.size.width,
        height:50,
        borderBottomWidth:1,
        borderBottomColor:'#e6e6e6',
        borderTopWidth:1,
        borderTopColor:'#e6e6e6',
        backgroundColor:'#fff'
    },
    buttonContent:{
        flex:5,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    buttonText:{
        fontSize:15,
        marginLeft:10
    }
})
export default commentDetailsStyle